# Generated by Django 3.1.3 on 2020-11-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_personal_portfolio', '0002_people_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='last_login',
        ),
    ]
